### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by Exadra37** [braver/FileIcons#1]
Thanks for this plugin :)

I installed it in ST3 build 3143 and some icons are missing.

Is anything else that needs to be  done?

![screenshot from 2018-04-17 21-15-02](https://user-images.githubusercontent.com/1745456/38894187-706bd9ee-4284-11e8-8aba-2381257e8ec5.png)

**Comment by braver** [comment]
Most of those probably don’t have a syntax (i.e. ST considers them “plain text”). This can be helped by setting  a syntax for their file extension. Or by installing packages. Dev builds of Sublime Text have a syntax package for .gitignore files for instance, and a git icon will show up for them. There is a package for the Dockerfile syntax in packagecontrol: https://packagecontrol.io/packages/Dockerfile%20Syntax%20Highlighting, installing that will probably enable the icon for that too.

**Comment by Exadra37** [comment]
Thanks for the quick reply.

Your tip works for some, but not for all.
