### ISSUE TITLE
Improve python and sublime icons

### ISSUE THREAD

**Issue by AmjadHD** [braver/FileIcons#13]
Hi can you update sublime icon to the latest version, and switch to the blue and yellow python icon ? I know this is very specific, but I couldn't do it on my own as I have no Idea about svg.

**Comment by braver** [comment]
I guess I could update the Sublime but I'm kinda attached to the old retro thing.

Icons are mono so we can generate different colors for them. Also makes them easier on the eyes. So we can't do blue-yellow for the Python icon.

**Comment by braver** [comment]
> So we can't do blue-yellow for the Python icon.

Or at least we should create an exception for it. It *can* be done..

**Comment by braver** [comment]
You're only going to see the Sublime icon if you have some syntaxes in place that differentiate those files. For most people they'll just show up as JSON and XML files. So I don't feel like it's much of a priority. And, like I said I'm kinda attached to the throwback icon. However, I'll accept a PR to update it to the current icon. I don't have an SVG source file to create one myself right. 

I've decided against doing multi-color icons. It would make the icons more distracting, it's a feature of FileIcons that everything is normalised to a somewhat harmonious color scheme with a handful colours. It also doesn't feel right to make an exception for Python while many icons were multi-colored originally.
