### ISSUE TITLE
Shebang detection

### ISSUE THREAD

**Issue by keggsmurph21** [braver/FileIcons#15]
Would it be possible to detect the filetype via the shebang for files without extension?  I'm poking around the repo now and don't see where the detection logic lives.  If you could point out where I could find that, I might be able to submit a PR for this functionality.  Thanks!

**Comment by braver** [comment]
The detection logic is internal to Sublime Text. It picks a syntax from either the extension or the first   line (e.g. to match a shebang). E.g. https://github.com/sublimehq/Packages/blob/master/ShellScript/Bash.sublime-syntax#L36

So if you need ST to see a file type from the shebang, you need to update the syntax to do so. FileIcons only maps the syntax to an icon.

**Comment by kmurphy4** [comment]
Ah, got it.  Thanks for the quick reply :)
