### ISSUE TITLE
Email icon

### ISSUE THREAD

**Issue by michaelblyons** [braver/FileIcons#20]
Can we add an envelope icon (optionally with `@` superimposed) for `text.email` and `text.eml` scopes?

**Comment by braver** [comment]
Sure, no problem, we just need to find / make a good 16x16px SVG.

**Comment by LollipopFt** [comment]
hi, could an exe one also be added? i think that would be nice, but it is fine if there isn't. thanks!

**Comment by braver** [comment]
> hi, could an exe one also be added

No, an exe is just a binary file and all binaries have the same "syntax" and therefore the same icon.

**Comment by braver** [comment]
I can’t find a syntax that provides those scopes, nor a good icon. A File Icon also has nothing. So this isn’t really actionable right now.

**Comment by michaelblyons** [comment]
https://github.com/mariozaizar/email.sublime-syntax/blob/master/email.sublime-syntax#L9

😢

**Comment by braver** [comment]
Now we’re talking

And this for the icon?
https://primer.style/design/foundations/icons/mail-16

**Comment by michaelblyons** [comment]
Good enough for me.

**Comment by braver** [comment]
<img width="152" alt="Scherm­afbeelding 2023-04-08 om 12 30 25" src="https://user-images.githubusercontent.com/2543659/230716428-51ec4175-eadc-4201-91b1-3c149f476d77.png">
