### ISSUE TITLE
Needing icon for ejs files

### ISSUE THREAD

**Issue by MrKhoaBean** [braver/FileIcons#22]

**Comment by braver** [comment]
ejs ?

**Comment by braver** [comment]
Look, I don't know what ejs is so help me out here. Preferably also provide an SVG/EPS/vector-whatever logo. Please re-open this issue when you have some info.

**Comment by MrKhoaBean** [comment]
Ejs is Embedded Js Templating
Here's your icon:
https://icon-icons.com/icon/file-type-ejs/130626
