### ISSUE TITLE
gulp-svg2png does not work with newer node versions

### ISSUE THREAD

**Issue by amendlik** [braver/FileIcons#27]
Running `npm install` produces the following errors:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'gulp-svg2png@2.0.2',
npm WARN EBADENGINE   required: { node: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.5.1', npm: '7.3.0' }
npm WARN EBADENGINE }
```

Running `npm run build` also fails:
```
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c gulp
```

**Comment by braver** [comment]
The package installs and builds just fine on 14.15 (LTS). I also don't get why it's complaining that 15.5 does not meet the requirement of ^6.0. It really should not be a problem. In any case, it's either a problem with your setup, or the specific dependency, and not something I can do much about I'm afraid.

**Comment by amendlik** [comment]
I can't explain this either. There is an [open issue](https://github.com/akoenig/gulp-svg2png/issues/39) for the product that says it is not compatible with Node 7. However, I cloned your repo to my Linux machine and it works just fine. Maybe it's something specific to Windows?

It's working for me on Linux, so I don't need to keep this issue open.

**Comment by braver** [comment]
Guess there is nothing we can do 🤷🏼‍♂️
