### ISSUE TITLE
I am viewing windows kind of icon for python files.

### ISSUE THREAD

**Issue by AdrijeGuha** [braver/FileIcons#28]
I don't know what happened, but I am not able to correct this. I could view the correct icon for my python file but after some time it changes to a completely different one. Please help be correct it. For reference, I have attached a screenshot below.

![Screenshot (141)](https://user-images.githubusercontent.com/67549713/110808286-d8019b80-82a9-11eb-8e81-5236f95fc2d6.png)

**Comment by braver** [comment]
That’s a multi colored icon, so it’s not from our package. Please check what packages you have installed and what syntax is assigned to the python files.
