### ISSUE TITLE
can figure out exactly how to customize ? 

### ISSUE THREAD

**Issue by younlok** [braver/FileIcons#42]
the theme that i am using it **halcyon**
**svelte** file are not saturated enough 
i want to make them more saturated how can i achieve that #

i think editing this package need more **docs**

**Comment by braver** [comment]
This package isn’t customizable. You can of course make your own build if you can figure out how to do so from the docs. But it doesn’t need more docs, what you’re trying to do is out of scope. You want A File Icon if you want more features, this one just works™️ out of the box.

**Comment by davidhq** [comment]
> the theme that i am using it **halcyon** **svelte** file are not saturated enough i want to make them more saturated how can i achieve that #
> 
> i think editing this package need more **docs**

You can:

a) fork the package
b) then

```
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages
git clone [your fork of FileIcons]
```

Then create file for your theme as described in docs (for example `Darkmatter.sublime-theme`), fill it from `Adaptive.sublime-theme` and restart Sublime

then replace icons `file_type_svelte.png    file_type_svelte@2x.png file_type_svelte@3x.png` inside `FileIcons/theme` with your versions.
