### ISSUE TITLE
Installing the mono version is still showing colorful  icons

### ISSUE THREAD

**Issue by dsego** [braver/FileIcons#5]
Thanks for making these, I love these icons and been using them  for quite a while. 
Wanted to try out the grayscale version but after uninstalling the original package and installing FileIcons - Mono,  the sidebar is  still showing colored icons. 

Sublime Text version 3175

**Comment by dsego** [comment]
I removed the original package and restarted Sublime multiple times. I'm gonna see if restarting the machine helps. Could be a caching issues  or  something specific to my computer. In any case, if you can't replicate it, feel free to close the issue. I'll let you know if I successfully resolve it.

**Comment by braver** [comment]
Yeah, this package doesn't actually "do" anything, it just provides an override that Sublime Text *should* pick up on by itself. If it doesn't "just work ™️" something is probably blocking the override. I think disabling the other FileIcons package isn't enough, you need to uninstall it. Check your installed packaged, installed via package control and those you installed manually. Also, switching the UI Theme might give it the kick it needs to get going again.

**Comment by dsego** [comment]
I understand how it works, I attempted to build my own before stumbling across this one ;). It was a very frustrating experience.

**Comment by JanHellwig** [comment]
I encountered the same issue and from what I can see, installing "FileIcons Mono" from package control gives you the same files as does installing "FileIcons". While the .sublime-package files are not binary-identical, they both contains colored .png files.

**Comment by braver** [comment]
I think I just tagged the wrong version. I created a new tag from the mono branch, should show up on package control soon. Sorry!

**Comment by jakubmikita** [comment]
@braver looks like the issue can back with the latest version. Package `mono` displays color icons.

PS. Thanks for the package!

**Comment by braver** [comment]
This is what I see with a clean install of the current Mono version. Maybe you also have the color version installed, or something else is weird. But it's not this package. 

<img width="249" alt="Scherm­afbeelding 2023-06-30 om 21 17 43" src="https://github.com/braver/FileIcons/assets/2543659/5dc8d1e9-cdef-4933-9664-3e1ab5def579">

**Comment by jakubmikita** [comment]
@braver I found the issue, it doesn't work with the [Material Theme](https://packagecontrol.io/packages/Material%20Theme), but it does work as expected with Default theme

**Comment by braver** [comment]
Ah, yes, Material Theme needs to do a little work. Or you can do so yourself: https://github.com/braver/FileIcons#customize
