### ISSUE TITLE
A few potentially missing icons

### ISSUE THREAD

**Issue by christopherpickering** [braver/FileIcons#52]
Thanks for this!

I have a few files missing icons, but I think some should be sharing icons that already exist:

- .coverage (new icon?) for https://coverage.readthedocs.io/en/6.4.1/
- .eslintignore > use a greyed version of eslint?
- .htmlhintrc > use the cogs?
- .jshintignore > use the cogs?
- .prettierignore > use the cogs?
- .prettierrc > use the cogs?
- .eslint.js > should use an eslint icon, not the js icon?
- .releaserc
- .styellintignore
- . (other dot files) > should default to cogs?
- *.sqlite > database icon?
- .python-version
- *.log > ?
- "nginx" nginx icon
- *.service > ?
- *.html.* > should use the html icon?

**Comment by braver** [comment]
Contrary to how "A File Icon" works we will not add syntaxes ourselves. So without specific packages something like all those configuration and ignore files simply register as "plain text". For the same reason `.eslint.js` is simply a JS file and doesn't get a specific icon. There is a package out there that does all that, this package has a different approach. However, if there is a package that adds an actual custom syntax for any of those, you can of course start a PR to add the icon.
