### ISSUE TITLE
Odin icon

### ISSUE THREAD

**Issue by dsego** [braver/FileIcons#59]
I've managed to create this svg icon from the site's logo  (https://odin-lang.org/logo.svg), basically extracted the first letter and changed the white to the brand blue color (unless this pkg has as predefined palette, wasn't sure). 

<img src="https://user-images.githubusercontent.com/578557/229073672-3ff14351-5449-40f0-ba55-e967fa539bcf.svg" width=64 />

There is another possible variant in the OLS package for VS Code.
https://github.com/DanielGavin/ols/blob/master/editors/vscode/fileicons/odin-file.svg
<img src="https://raw.githubusercontent.com/DanielGavin/ols/master/editors/vscode/fileicons/odin-file.svg" width=64 />

**Comment by braver** [comment]
I presume this is the syntax for it?

https://packagecontrol.io/packages/Odin

**Comment by dsego** [comment]
Yes, that looks to be it.

**Comment by hristo-kanchev** [comment]
I was literally just searching for this repo in order to create this request 😄 

Happy to see that it will be added ^^

**Comment by dsego** [comment]
Looks awesome, thanks! 🎉 🎉 🎉
