### ISSUE TITLE
Simpler Graphviz icon

### ISSUE THREAD

**Issue by michaelblyons** [braver/FileIcons#6]
The Graphviz SVG is super-complex and not very readable at the size of a sidebar icon. Can we take the favicon from the graphviz.org website and adapt that instead?

**Comment by braver** [comment]
fixed in #8

**Comment by michaelblyons** [comment]
Can you (re)tag the release as `color-1.1.1` so Package Control picks it up?

**Comment by braver** [comment]
Dang, totally forgot I set it up like that. Thanks!
