### ISSUE TITLE
Make color for mono icons configurable

### ISSUE THREAD

**Issue by jwortmann** [braver/FileIcons#60]
For the FileIcons Mono variant, the color is currently incorporated in the PNG files, as defined in the https://github.com/braver/FileIcons/blob/mono/build/colors.json file used for building the PNGs. This means that it cannot be changed by users. And the enforced color might result in a poor contrast for 3rd-party themes.

This happens for example with my [Brackets theme](https://packagecontrol.io/packages/Theme%20-%20Brackets), if you look very closely, you can see that the icons are there and rendered correctly, but they are almost invisible, because I use almost the same color for the sidebar background:

![icons](https://user-images.githubusercontent.com/6579999/230515736-d21ef591-d75e-4e4e-8dcc-2f76805f83c0.png)

I think there is a better way to apply the color for FileIcons Mono:
The PNGs must use pure white `#ffffff` for the icon color, and then you can set the actual color via the texture `tint` in the theme, i.e. in this case adjust the following line in all three provided theme files to `"layer0.tint": "hsl(0, 0%, 50%)"` if you want to keep the same color
https://github.com/braver/FileIcons/blob/dee18cdfa3811aa35c45fc4900b5f17158cf5cbd/theme/Adaptive.sublime-theme#L4

This would allow users of third-party themes to adjust the color to what they like (or also set a different color for Default & Adaptive themes).

Actually I have not tested it, because I don't have Rust installed at the moment, but I'm pretty confident that it should work. If you want, I could test it and provide a PR if you agree.

**Comment by jwortmann** [comment]
The downside would be, for users who have FileIcons Mono installed and already configured to use it with a third-party theme, then they have probably just copied and renamed one of the provided theme files, e.g. https://github.com/braver/FileIcons/blob/mono/theme/Adaptive.sublime-theme.

So when the package gets updated, it would still work fine and show the default color for the built-in themes, but the icons for the third-party theme users will be pure white then. You could add an update message for the package via Package Control's `messages.json` and describe for affected users how to restore the old color (by adjusting the line I referenced above).

**Comment by braver** [comment]
Sounds like a smart approach! It would be a breaking change, but I think we can manage that with proper communication.

**Comment by braver** [comment]
> but the icons for the third-party theme users will be pure white then

Actually, they won't because it will probably still have a level of opacity that makes them blend in. It might mean a little higher contrast than they're used to. But I think it's a great improvement all around to put all of the color and contrast choice in the theme and not in the image itself 👍🏻

**Comment by braver** [comment]
Thanks, this is great stuff! Shipping immediately.

**Comment by jwortmann** [comment]
I noticed two other things, one of it might be helpful to know for other users of third-party themes.

1. I didn't get the update message from Package Control. Perhaps you immediately pushed another tag v2.0.1, and then the only update from Package Control was to this latest version. Apparently the message will only be shown if the update is to the particular matching version, i.e. v2.0.0 in this case. Or it was some issue on my side, I don't know.

2. There is a minor limitation to the intended approach to modifiy the color for third-party themes. Namely, if there exists already a similar rule like for example
    ```jsonc
    {
        "class": "icon_file_type",
        "layer0.tint": "var(sidebar_file_icon)",
        "layer0.opacity": 1.0,
        "content_margin": 8
    },
    ```
    in the original theme, and the theme (package) name ordered later in the alphabet than "FileIcons Mono", then the customization file in the `Packages/FileIcons Mono/theme/` folder is not sufficient to set the color. This is probably the case for most themes, which names usually begin with "Theme - ...". The reason why it happens, is Sublime's package load order, i.e. first it loads the Default package, then all shipped and installed packages in alphabetical order, and at last the User package. The theme rules from different files are just appended in order, and so the one contained in the original theme, like the example above, will take precedence over the one you would manually put into the `Packages/FileIcons Mono/theme/` folder. In one way this is also kind of an advantage; e.g. for my own theme, it was sufficient for the customization file to only contain an empty array
    ```json
    []
    ```
    and the icon color set in the original theme got applied automatically. And there is also an easy workaround, if you do want to change the color directly. In this case you can just put another customization file with the same name into the `Packages/User/` folder, which will then be loaded at last, and so the color set therein will take precedence.

So now I wonder whether you would accept a pull request to include a `Brackets.hidden-theme` (my own theme from the link above) file, containing just the empty JSON array, into this repository? Then the users of my theme would have to do nothing but install this package if they like to have the file icons, and it would immediately work without the need for any additional installation/customization steps. And the `.hidden-theme` file extension would prevent it to show up in the theme picker for users who don't have my theme installed. On the other hand, this might open up the door for other theme developers to add similar files into this repository, in order to make it immediately work for their third-party themes (not sure if this would be a good or a bad thing).

**Comment by braver** [comment]
> I didn't get the update message from Package Control

Hmmm, my understanding of it is that you would get messages for all versions including any versions you skipped. But that may not be true. 

There is no solid way around the load order of packages. This is why "A File Icon" starts with an A, and creates (or at least used to create, haven't checked that one in years) a package directory starting "zzz" with output. Shenanigans IMO. For valid reasons of course, but my packages try to stay away from that. Supporting third party themes was never a big goal, but it can be achieved as described in the Readme, and in your comment here. 

Honestly, if you're a theme developer and you want to incorporate the icons in this package, don't rely on this package being installed. Instead just copy over the icons from the [theme directory](https://github.com/braver/FileIcons/tree/master/theme), as well as the [preferences](https://github.com/braver/FileIcons/tree/master/preferences), to your project. Sure it's a little bit of work and you want to sync up every year or so, but nothing major has changed besides a handful of niche icons since 2020. You could also submodule my repo. Should be easy enough to script up a pipeline that syncs your icons. That way my package can't break yours in any way. And you gain a lot of flexibility, like making the colors match your theme exactly.
