### ISSUE TITLE
Feature request: Icon for Symbolic links

### ISSUE THREAD

**Issue by anatanna** [braver/FileIcons#65]
Hi, 
Thanks for really nice and useful package!
I wonder if it is possible to add a separate icon for symlinks ? It would be great to differ "real file" from its "reference".
Thanks,
A.

**Comment by braver** [comment]
No that's not possible. We only add file icons, the icons for directories are just the default ones. Sublime itself doesn't indicate symlinks differently so there is no way for us to do anything here.
